import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/header/header";
import Footer from "@/components/ui/footer/footer";

import { Inter,Roboto } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight:['400','700'], variable:'--font-roboto',});

export const metadata: Metadata = {
  title: "Hackhathon Ecommerce Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(inter.className, roboto.className)}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
